[package]
name = "maple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
rand = "0.8.5"
needletail = "0.5.1"
nalgebra = "0.32.3"

[profile.release]
debug = 1
